language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t deedsgrom48/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true deedsgrom48/react-test npm test

after_success:
  - docker build -t deedsgrom48/multi-client ./client
  - docker build -t deedsgrom48/multi-nginx ./nginx
  - docker build -t deedsgrom48/multi-server ./server
  - docker build -t deedsgrom48/multi-worker ./worker
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  #take those images and push them to docker
  - docker push deedsgrom48/multi-client
  - docker push deedsgrom48/multi-nginx
  - docker push deedsgrom48/multi-server
  - docker push deedsgrom48/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-559567280506"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"
